name: chimera-env
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.1.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.0=h7b32b05_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.0=py312h5eee18b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - python=3.12.9=h5148396_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - pyzmq=26.2.0=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py312h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - alabaster==1.0.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - binaryornot==0.4.4
      - bleach==6.2.0
      - blinker==1.9.0
      - brotli==1.1.0
      - build==1.2.2.post1
      - cachetools==6.1.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - citeproc-py==0.8.2
      - clabtoolkit==0.3.4
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - devicetorch==0.1.13
      - dipy==1.11.0
      - docutils==0.21.2
      - duecredit==0.10.2
      - et-xmlfile==2.0.0
      - fastapi==0.116.1
      - fastjsonschema==2.21.1
      - ffmpy==0.6.1
      - filelock==3.13.1
      - fonttools==4.57.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - fury==0.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - groovy==0.1.2
      - h11==0.14.0
      - h5py==3.14.0
      - hf-xet==1.1.9
      - httpcore==1.0.8
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - imageio==2.37.0
      - imagesize==1.4.1
      - iniconfig==2.1.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.5
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jinja2-time==0.2.0
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==1.1.11
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - looseversion==1.3.0
      - lxml==5.3.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mistune==3.1.3
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - mycolorpy==1.5.1
      - mypy-extensions==1.0.0
      - myst-parser==4.0.1
      - narwhals==1.46.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - nibabel==5.3.2
      - nigsp==0.19.0
      - nilearn==0.12.0
      - ninja==1.13.0
      - notebook==7.4.0
      - notebook-shim==0.2.4
      - numpy==2.3.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - openpyxl==3.1.5
      - orderly-set==5.4.0
      - orjson==3.11.3
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.1
      - pandas-flavor==0.7.0
      - pandocfilters==1.5.1
      - patsy==1.0.1
      - pillow==11.3.0
      - pingouin==0.5.5
      - pip==25.2
      - pluggy==1.5.0
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - propcache==0.3.1
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pybids==0.19.0
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pydicom==3.0.1
      - pydub==0.25.1
      - pygame==2.6.1
      - pygltflib==1.16.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyproject-hooks==1.2.0
      - pytest==8.3.5
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyvista==0.46.3
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.1.0
      - roman-numerals-py==3.1.0
      - rpds-py==0.24.0
      - ruff==0.12.11
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.16.0
      - scooby==0.10.0
      - screeninfo==0.8.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - setuptools==80.9.0
      - setuptools-scm==8.2.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - soupsieve==2.6
      - sphinx==8.2.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - starlette==0.47.3
      - statsmodels==0.14.5
      - streamlit==1.46.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - templateflow==25.0.3
      - terminado==0.18.1
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tifffile==2025.6.11
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - tqdm==4.67.1
      - trame==3.10.2
      - trame-client==3.9.1
      - trame-common==1.0.0
      - trame-jupyter-extension==2.1.4
      - trame-server==3.4.2
      - trame-vtk==2.8.17
      - trame-vuetify==3.0.1
      - trx-python==0.3
      - typer==0.16.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.14.1
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.4.0
      - uvicorn==0.35.0
      - vtk==9.3.1
      - watchdog==6.0.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - widgetsnbextension==3.6.10
      - wrapt==1.17.2
      - wslink==2.3.4
      - xarray==2025.8.0
      - xformers==0.0.27
      - yarl==1.19.0
